### ISSUE TITLE
 ENOENT: no such file or directory error on Action Summary

### ISSUE THREAD

**Issue by kuldeep3** [10up/wpcs-action#42]
### Describe your question

I am using the below code for adding linting checks using github actions, but getting ENOENT error on action summary

```
name: WordPress Coding Standard Check

on: pull_request


jobs:
  phpcs:
      name: VIPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: VIPCS check
          uses: 10up/wpcs-action@stable
          with:
            standard: 'WordPress-VIP-Go'
            use_local_config: true
            extra_args: '--report-json=./phpcs.json'
            paths: ${{ github.event.pull_request.changed_files }}
        - name: Update summary
          run: |
            npm i -g github:10up/phpcs-json-to-md
            phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
            cat phpcs.md >> $GITHUB_STEP_SUMMARY
          if: always()
```

Is there something wrong in the implementation? Also, is there a way I can only check the files that are in the PR instead of whole code?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@kuldeep3 try quotes around the `use_local_config` value.  I'm checking on the `paths` arg to ensure that's correctly formatted as well.

**Comment by raulillana** [comment]
This problem is not resolved with quotes.

![Captura de pantalla 2024-04-15 a las 14 42 05](https://github.com/10up/wpcs-action/assets/1171669/ac27af92-4224-4926-a7a9-71b9278daf00)

EDIT: BTW the solution for me was to get the right params into PHPCS so the JSON file is generated correctly. Also using NPX instead of NPM.

**Comment by B-Interactive** [comment]
I can confirm I'm now encountering the same issue.  I've not changed my `.yml` file, but it stopped working recently.  I'm using what is almost an exact copy/paste of the example:
```yml
name: WordPress Coding Standards

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            standard: 'WordPress'
            extra_args: '--report-json=./phpcs.json'
        - name: Update summary
          run: |
            npm i -g github:10up/phpcs-json-to-md
            phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
            cat phpcs.md >> $GITHUB_STEP_SUMMARY
          if: always()
```

Produces this error:
```sh
Run npm i -g github:10up/phpcs-json-to-md

added 54 packages in 4s

22 packages are looking for funding
  run `npm fund` for details
Error: Can not read the JSON file.
Error: ENOENT: no such file or directory, open './phpcs.json'
    at Object.readFileSync (node:fs:449:20)
    at run (file:///usr/local/lib/node_modules/@10up/phpcs-json-to-md/cli.js:50:19)
    at file:///usr/local/lib/node_modules/@10up/phpcs-json-to-md/cli.js:89:1
    at ModuleJob.run (node:internal/modules/esm/module_job:263:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:540:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './phpcs.json'
}
Error: Process completed with exit code 1.
```
