### ISSUE TITLE
Support 10up-Default

### ISSUE THREAD

**Issue by dinhtungdu** [10up/wpcs-action#9]
### Is your enhancement related to a problem? Please describe.

Support https://github.com/10up/phpcs-composer, so if a repository using the `10up-Default` ruleset only need to set the `standard` to `10up-Default`.

### Designs

Ideal workflow:

```
name: PHPCS check

on: pull_request

jobs:
  phpcs:
      name: 10up PHPCS ruleset
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: WPCS check
          uses: 10up/wpcs-action@stable
            with:
              standard: '10up-Default'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
